import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Fonts load kiye gaye
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Page metadata
export const metadata = {
  title: "Watt Website",
  description: "Generated by create next app",
};

// RootLayout sab routes wrap karta hai
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
